### ISSUE TITLE
Localhost not starting 

### ISSUE THREAD

**Issue by andrei10k** [cypress-io/github-action#100]
Hey man

I really appreciate your work. I'm trying to setup a github workflow for running cypress tests after a push to master. I manage to make it work on a staging environment but i'm trying to make it work on localhost. So i'm using: 

```yml
name: End-to-end tests
on: 
  push:
    branches: master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          group: 'Ideal'
          start: yarn start
          wait-on: 'http://localhost:8080'
          env: stage=LOCAL
        env:
          CYPRESS_RECORD_KEY: 'secret_key'
```
and my yarn start script is: `cross-env NODE_ENV=development webpack-dev-server`

I suppose it got something to do with webpack-dev-server? It's failing to start the local server with the following error: 
```
events.js:298
2020-02-29T12:49:52.3966975Z       throw er; // Unhandled 'error' event
2020-02-29T12:49:52.3967165Z       ^
2020-02-29T12:49:52.3967216Z 
2020-02-29T12:49:52.3967352Z Error: spawn chrome ENOENT
2020-02-29T12:49:52.3967452Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
2020-02-29T12:49:52.3967925Z     at onErrorNT (internal/child_process.js:469:16)
2020-02-29T12:49:52.3968072Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-02-29T12:49:52.3968442Z Emitted 'error' event on ChildProcess instance at:
2020-02-29T12:49:52.3968694Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
2020-02-29T12:49:52.3968864Z     at onErrorNT (internal/child_process.js:469:16)
2020-02-29T12:49:52.3969079Z     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
2020-02-29T12:49:52.3969407Z   errno: 'ENOENT',
2020-02-29T12:49:52.3969643Z   code: 'ENOENT',
2020-02-29T12:49:52.3969946Z   syscall: 'spawn chrome',
2020-02-29T12:49:52.3970235Z   path: 'chrome',
2020-02-29T12:49:52.3970610Z   spawnargs: [ 'http://localhost:8080/' ]
2020-02-29T12:49:52.3970722Z }
2020-02-29T12:49:52.4055372Z npm ERR! code ELIFECYCLE
2020-02-29T12:49:52.4056006Z npm ERR! errno 1
2020-02-29T12:49:52.4067053Z npm ERR! ideal-react@1.0.0 start: `cross-env NODE_ENV=development webpack-dev-server`
2020-02-29T12:49:52.4067818Z npm ERR! Exit status 1
2020-02-29T12:49:52.4068010Z npm ERR! 
2020-02-29T12:49:52.4069022Z npm ERR! Failed at the ideal-react@1.0.0 start script.
2020-02-29T12:49:52.4069280Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I'd really appreciate your help. 

Thanks

**Comment by jennifer-shehane** [comment]
The error message indicates this is failing due to the `ideal-react@1.0.0 start script`, does not look related to Cypress. Closing since not related to Cypress specifically.

**Comment by andrei10k** [comment]
If you look at the yaml file it's exactly as in documentation. I already pasted the start script, which is just opening a dev server with webpack. If it's a problem with webpack you should add this in your documentation. Anyway, thanks a lot!

**Comment by bahmutov** [comment]
@andrei10k when you run the start script locally - does it open the page in your local browser? Because it seems like it does. From the log it seems the webpack dev server tries to do that and fails. Disable opening the browser and it should work.
