### ISSUE TITLE
Intermittent failure where "Browser: 'chrome' was not found on your system"

### ISSUE THREAD

**Issue by lukebrowne** [cypress-io/github-action#142]
Using the config:
```yaml
        - name: Run Cypress tests
          uses: cypress-io/github-action@v1
          with:
            browser: chrome
            headless: true
            working-directory: client
```

We're intermittently getting the error:
```
Can't run because you've entered an invalid browser name.

Browser: 'chrome' was not found on your system.

Available browsers found are: firefox, electron
```

Here are the full logs from this step:
```
2020-05-15T10:26:58.0387293Z restoring cache /home/runner/.npm
2020-05-15T10:26:58.0388228Z primary key npm-linux-x64-610886dc8cf002e8d077277567b371b6ab5359d795721f4b9aac4d9cc01d8fe7c9d8128b3b39f8eb7966c473499202d90e7cbdd274b806348043a1b3ea8d4278
2020-05-15T10:26:58.0656994Z restoring cache /home/runner/.cache/Cypress
2020-05-15T10:26:58.0657828Z primary key cypress-linux-x64-610886dc8cf002e8d077277567b371b6ab5359d795721f4b9aac4d9cc01d8fe7c9d8128b3b39f8eb7966c473499202d90e7cbdd274b806348043a1b3ea8d4278
2020-05-15T10:27:00.2595459Z [command]/bin/tar -xz -f /home/runner/work/_temp/077c6ebd-b618-4b59-98f6-3c507210987d/cache.tgz -C /home/runner/.npm
2020-05-15T10:27:01.9490605Z Cache restored from key: npm-linux-x64-610886dc8cf002e8d077277567b371b6ab5359d795721f4b9aac4d9cc01d8fe7c9d8128b3b39f8eb7966c473499202d90e7cbdd274b806348043a1b3ea8d4278
2020-05-15T10:27:05.2394731Z [command]/bin/tar -xz -f /home/runner/work/_temp/69e71085-d5ff-4d02-91e2-d344a2b892ea/cache.tgz -C /home/runner/.cache/Cypress
2020-05-15T10:27:19.5163826Z Cache restored from key: cypress-linux-x64-fa4342b0cc087745aced1b17cc39f31ad9a9986f1fee9bcecb4edcdee7c5d34fea88f4068c1532a16e98fcbe43a02f2a3e43c4a6042ee9097539ff0124154eb6
2020-05-15T10:27:19.5232257Z [command]/usr/local/bin/npm ci
2020-05-15T10:28:03.3254793Z 
2020-05-15T10:28:03.3255674Z > fsevents@1.2.11 install /home/runner/work/informed360/informed360/client/node_modules/fsevents
2020-05-15T10:28:03.3256731Z > node-gyp rebuild
2020-05-15T10:28:03.3256796Z 
2020-05-15T10:28:07.6763311Z make: Entering directory '/home/runner/work/informed360/informed360/client/node_modules/fsevents/build'
2020-05-15T10:28:07.7199265Z   SOLINK_MODULE(target) Release/obj.target/.node
2020-05-15T10:28:07.7810544Z   COPY Release/.node
2020-05-15T10:28:07.7901172Z make: Leaving directory '/home/runner/work/informed360/informed360/client/node_modules/fsevents/build'
2020-05-15T10:28:07.9213035Z 
2020-05-15T10:28:07.9214256Z > styled-components@3.4.10 postinstall /home/runner/work/informed360/informed360/client/node_modules/styled-components
2020-05-15T10:28:07.9214553Z > node ./scripts/postinstall.js || exit 0
2020-05-15T10:28:07.9214750Z 
2020-05-15T10:28:07.9680015Z Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components
2020-05-15T10:28:08.0276321Z 
2020-05-15T10:28:08.0277688Z > core-js@2.6.11 postinstall /home/runner/work/informed360/informed360/client/node_modules/attr-accept/node_modules/core-js
2020-05-15T10:28:08.0278328Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:08.0278627Z 
2020-05-15T10:28:08.0871656Z 
2020-05-15T10:28:08.0873257Z > core-js@2.6.11 postinstall /home/runner/work/informed360/informed360/client/node_modules/@babel/runtime-corejs2/node_modules/core-js
2020-05-15T10:28:08.0873559Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:08.0873907Z 
2020-05-15T10:28:08.3807164Z 
2020-05-15T10:28:08.3808481Z > node-sass@4.12.0 install /home/runner/work/informed360/informed360/client/node_modules/node-sass
2020-05-15T10:28:08.3808839Z > node scripts/install.js
2020-05-15T10:28:08.3809063Z 
2020-05-15T10:28:09.6050749Z Cached binary found at /home/runner/.npm/_cacache/node-sass/4.12.0/linux-x64-72_binding.node
2020-05-15T10:28:09.6230520Z 
2020-05-15T10:28:09.6231684Z > node-sass@4.12.0 postinstall /home/runner/work/informed360/informed360/client/node_modules/node-sass
2020-05-15T10:28:09.6232235Z > node scripts/build.js
2020-05-15T10:28:09.6232473Z 
2020-05-15T10:28:09.7553129Z Binary found at /home/runner/work/informed360/informed360/client/node_modules/node-sass/vendor/linux-x64-72/binding.node
2020-05-15T10:28:09.7555717Z Testing binary
2020-05-15T10:28:09.8583391Z Binary is fine
2020-05-15T10:28:09.9606353Z 
2020-05-15T10:28:09.9607779Z > core-js@2.6.11 postinstall /home/runner/work/informed360/informed360/client/node_modules/draft-js/node_modules/core-js
2020-05-15T10:28:09.9608348Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:09.9608608Z 
2020-05-15T10:28:10.3457168Z 
2020-05-15T10:28:10.3457887Z > husky@0.14.3 install /home/runner/work/informed360/informed360/client/node_modules/husky
2020-05-15T10:28:10.3458193Z > node ./bin/install.js
2020-05-15T10:28:10.3458411Z 
2020-05-15T10:28:10.3908302Z husky
2020-05-15T10:28:10.3910983Z CI detected, skipping Git hooks installation
2020-05-15T10:28:10.4728435Z 
2020-05-15T10:28:10.4728945Z > cypress@4.4.1 postinstall /home/runner/work/informed360/informed360/client/node_modules/cypress
2020-05-15T10:28:10.4729701Z > node index.js --exec install
2020-05-15T10:28:10.4729841Z 
2020-05-15T10:28:10.8270544Z Note: Overriding Cypress cache directory to: /home/runner/.cache/Cypress
2020-05-15T10:28:10.8271193Z 
2020-05-15T10:28:10.8271498Z       Previous installs of Cypress may not be found.
2020-05-15T10:28:10.8272977Z 
2020-05-15T10:28:10.8473508Z Installing Cypress (version: 4.4.1)
2020-05-15T10:28:10.8476334Z 
2020-05-15T10:28:10.8503155Z [?25l[10:28:10]  Downloading Cypress     [started]
2020-05-15T10:28:12.5779466Z [10:28:12]  Downloading Cypress     [completed]
2020-05-15T10:28:12.5785850Z [10:28:12]  Unzipping Cypress       [started]
2020-05-15T10:28:20.3042082Z [10:28:20]  Unzipping Cypress       [completed]
2020-05-15T10:28:20.3043453Z [10:28:20]  Finishing Installation  [started]
2020-05-15T10:28:20.3286983Z [10:28:20]  Finishing Installation  [completed]
2020-05-15T10:28:21.3320578Z [?25h
2020-05-15T10:28:21.3320830Z You can now open Cypress by running: node_modules/.bin/cypress open
2020-05-15T10:28:21.3320956Z 
2020-05-15T10:28:21.3321373Z https://on.cypress.io/installing-cypress
2020-05-15T10:28:21.3321487Z 
2020-05-15T10:28:21.4050929Z [?25h
2020-05-15T10:28:21.4052128Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/react/node_modules/core-js
2020-05-15T10:28:21.4052435Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.4052517Z 
2020-05-15T10:28:21.5281387Z 
2020-05-15T10:28:21.5287149Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/node-logger/node_modules/core-js
2020-05-15T10:28:21.5287855Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.5288220Z 
2020-05-15T10:28:21.6432864Z 
2020-05-15T10:28:21.6434366Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/lazy-universal-dotenv/node_modules/core-js
2020-05-15T10:28:21.6434980Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.6435241Z 
2020-05-15T10:28:21.7138603Z 
2020-05-15T10:28:21.7139456Z > ejs@2.7.4 postinstall /home/runner/work/informed360/informed360/client/node_modules/ejs
2020-05-15T10:28:21.7139620Z > node ./postinstall.js
2020-05-15T10:28:21.7139693Z 
2020-05-15T10:28:21.7797011Z 
2020-05-15T10:28:21.7798773Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/core/node_modules/core-js
2020-05-15T10:28:21.7799363Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.7799685Z 
2020-05-15T10:28:21.8786143Z 
2020-05-15T10:28:21.8787375Z > core-js-pure@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/core-js-pure
2020-05-15T10:28:21.8787915Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.8788172Z 
2020-05-15T10:28:21.9252420Z 
2020-05-15T10:28:21.9253589Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/ui/node_modules/core-js
2020-05-15T10:28:21.9254287Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.9254511Z 
2020-05-15T10:28:21.9684689Z 
2020-05-15T10:28:21.9686068Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/theming/node_modules/core-js
2020-05-15T10:28:21.9686682Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:21.9687019Z 
2020-05-15T10:28:22.0160910Z 
2020-05-15T10:28:22.0162086Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/client-logger/node_modules/core-js
2020-05-15T10:28:22.0162540Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.0162761Z 
2020-05-15T10:28:22.0671475Z 
2020-05-15T10:28:22.0672618Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/router/node_modules/core-js
2020-05-15T10:28:22.0673106Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.0673392Z 
2020-05-15T10:28:22.1133526Z 
2020-05-15T10:28:22.1135039Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/core-events/node_modules/core-js
2020-05-15T10:28:22.1135661Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.1135879Z 
2020-05-15T10:28:22.1661960Z 
2020-05-15T10:28:22.1663460Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/simplebar/node_modules/core-js
2020-05-15T10:28:22.1664001Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.1664255Z 
2020-05-15T10:28:22.2267640Z 
2020-05-15T10:28:22.2268973Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/components/node_modules/core-js
2020-05-15T10:28:22.2270169Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.2270460Z 
2020-05-15T10:28:22.2748135Z 
2020-05-15T10:28:22.2749608Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/channels/node_modules/core-js
2020-05-15T10:28:22.2750780Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.2750960Z 
2020-05-15T10:28:22.3250038Z 
2020-05-15T10:28:22.3251446Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/api/node_modules/core-js
2020-05-15T10:28:22.3252232Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.3252497Z 
2020-05-15T10:28:22.3858946Z 
2020-05-15T10:28:22.3860308Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/addons/node_modules/core-js
2020-05-15T10:28:22.3861706Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.3862642Z 
2020-05-15T10:28:22.4324726Z 
2020-05-15T10:28:22.4326449Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/channel-postmessage/node_modules/core-js
2020-05-15T10:28:22.4326895Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.4326981Z 
2020-05-15T10:28:22.4814684Z 
2020-05-15T10:28:22.4816172Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/client-api/node_modules/core-js
2020-05-15T10:28:22.4816787Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.4817095Z 
2020-05-15T10:28:22.5296137Z 
2020-05-15T10:28:22.5297918Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/addon-links/node_modules/core-js
2020-05-15T10:28:22.5298589Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.5298995Z 
2020-05-15T10:28:22.6132001Z 
2020-05-15T10:28:22.6133201Z > core-js@2.6.11 postinstall /home/runner/work/informed360/informed360/client/node_modules/babel-runtime/node_modules/core-js
2020-05-15T10:28:22.6133638Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.6134047Z 
2020-05-15T10:28:22.6967512Z 
2020-05-15T10:28:22.6968994Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/addon-docs/node_modules/core-js
2020-05-15T10:28:22.6969596Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.6969896Z 
2020-05-15T10:28:22.7535679Z 
2020-05-15T10:28:22.7537167Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/source-loader/node_modules/core-js
2020-05-15T10:28:22.7537634Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.7537859Z 
2020-05-15T10:28:22.8034902Z 
2020-05-15T10:28:22.8036169Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/postinstall/node_modules/core-js
2020-05-15T10:28:22.8036647Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.8036879Z 
2020-05-15T10:28:22.8700226Z 
2020-05-15T10:28:22.8701290Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@storybook/addon-actions/node_modules/core-js
2020-05-15T10:28:22.8701760Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.8701937Z 
2020-05-15T10:28:22.9272155Z 
2020-05-15T10:28:22.9273284Z > core-js@2.6.11 postinstall /home/runner/work/informed360/informed360/client/node_modules/@babel/polyfill/node_modules/core-js
2020-05-15T10:28:22.9273681Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.9273899Z 
2020-05-15T10:28:22.9739441Z 
2020-05-15T10:28:22.9740768Z > core-js@3.6.5 postinstall /home/runner/work/informed360/informed360/client/node_modules/@babel/node/node_modules/core-js
2020-05-15T10:28:22.9741325Z > node -e "try{require('./postinstall')}catch(e){}"
2020-05-15T10:28:22.9741581Z 
2020-05-15T10:28:23.0186270Z added 2652 packages in 42.679s
2020-05-15T10:28:23.0454943Z [command]/usr/local/bin/npx cypress verify
2020-05-15T10:28:23.4087389Z 
2020-05-15T10:28:23.4124976Z [?25l[10:28:23]  Verifying Cypress can run /home/runner/.cache/Cypress/4.4.1/Cypress [started]
2020-05-15T10:28:40.0844296Z [10:28:40]  Verifying Cypress can run /home/runner/.cache/Cypress/4.4.1/Cypress [completed]
2020-05-15T10:28:40.0934034Z [?25h[?25h::debug::saving NPM modules
2020-05-15T10:28:40.0935987Z saving cache path /home/runner/.npm
2020-05-15T10:28:40.0937167Z primary key npm-linux-x64-610886dc8cf002e8d077277567b371b6ab5359d795721f4b9aac4d9cc01d8fe7c9d8128b3b39f8eb7966c473499202d90e7cbdd274b806348043a1b3ea8d4278
2020-05-15T10:28:40.0965375Z [command]/bin/tar -cz -f /home/runner/work/_temp/8ad65068-d1c3-4d4b-a623-faba58ba6ea1/cache.tgz -C /home/runner/.npm .
2020-05-15T10:28:48.9161673Z Cache saved successfully
2020-05-15T10:28:48.9218942Z saving cache path /home/runner/.cache/Cypress
2020-05-15T10:28:48.9220850Z primary key cypress-linux-x64-610886dc8cf002e8d077277567b371b6ab5359d795721f4b9aac4d9cc01d8fe7c9d8128b3b39f8eb7966c473499202d90e7cbdd274b806348043a1b3ea8d4278
2020-05-15T10:28:48.9235922Z [command]/bin/tar -cz -f /home/runner/work/_temp/f0e5ff25-2826-44f7-b871-8d45fec95cf0/cache.tgz -C /home/runner/.cache/Cypress .
2020-05-15T10:29:51.6022262Z ##[warning]Cache size of 458753248 bytes is over the 400MB limit, not saving cache.
2020-05-15T10:29:51.6028973Z Cypress test command: npx cypress run --headless --config-file cypress.json --browser chrome
2020-05-15T10:29:51.6058594Z [command]/usr/local/bin/npx cypress run --headless --config-file cypress.json --browser chrome
2020-05-15T10:30:05.7171141Z [31mCan't run because you've entered an invalid browser name.[39m
2020-05-15T10:30:05.7172110Z [31m[39m
2020-05-15T10:30:05.7173111Z [31mBrowser: 'chrome' was not found on your system.[39m
2020-05-15T10:30:05.7173443Z [31m[39m
2020-05-15T10:30:05.7173739Z [31mAvailable browsers found are: firefox, electron[39m
2020-05-15T10:30:05.7775943Z Error: The process '/usr/local/bin/npx' failed with exit code 1
2020-05-15T10:30:05.7776772Z     at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1188:25)
2020-05-15T10:30:05.7777723Z     at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1171:18)
2020-05-15T10:30:05.7778492Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1071:27)
2020-05-15T10:30:05.7778843Z     at ChildProcess.emit (events.js:210:5)
2020-05-15T10:30:05.7779364Z     at maybeClose (internal/child_process.js:1021:16)
2020-05-15T10:30:05.7779692Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-05-15T10:30:05.7782498Z ##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

**Comment by aaronmeder** [comment]
I am also experiencing the same error.

I am running cypress using Github Actions on a schedule every 2 hours and receive this error about once a day. All of the other times it would work just fine without any code or workflow modifications in between.

**Comment by jennifer-shehane** [comment]
We've increased the timeout for the --version command when attempting to find the browser here: https://github.com/cypress-io/cypress/pull/7366 We're hoping this will resolve the issue.

This should be part of our next Cypress release. I'm not sure what about GitHub Actions is making this crop up lately.

**Comment by lukebrowne** [comment]
Thanks for looking into this @jennifer-shehane

**Comment by aaronmeder** [comment]
Thanks @jennifer-shehane!

Just seen that the update you suggested has been released in Cypress 4.6.0 but my action still uses 4.5.0. Can I force it to switch to the newer version?
It seems to be loading it from the cache: 

Part of my Github Actions log:
`Cypress 4.5.0 is installed in /home/runner/.cache/Cypress/4.5.0`

**Comment by DlgSHi** [comment]
Did you try to use the `container: cypress/browsers:node12.13.0-chrome80-ff74` ? with already installed `chrome` and `FF` ?

**Comment by jennifer-shehane** [comment]
Closing as resolved. If you're still seeing this issue in 4.6.0+, please open a new issue.
