### ISSUE TITLE
Running fails with Cypress 4.8.0 but works with 4.7.0

### ISSUE THREAD

**Issue by sazzer** [cypress-io/github-action#159]
I've just updated my project to Cypress 4.8.0 and my Github Action started failing with:
```
Exit code: 1
Command: node index.js --exec install
Arguments: 
Directory: /home/runner/work/multiverse/multiverse/e2e/node_modules/@types/testing-library__cypress/node_modules/cypress
Output:
Note: Overriding Cypress cache directory to: /home/runner/.cache/Cypress

      Previous installs of Cypress may not be found.

Installing Cypress (version: 4.7.0)

25l[17:19:37]  Downloading Cypress     [started]
[17:19:39]  Downloading Cypress     [failed]
25hThe Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.7.0?platform=linux&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 8f22b6d7ef2e005aa367efa27a9813804c9b30c154654c8c990785439657167b3d8ce4daf9dc18e52fbdb958070f6f6ecdfc0ae967d55d9fbd8fc32d56660631
Computed checksum: f3061616c545abc35ddeab4fa35a077440d5f93aa8b6f4df9e874bf0bb8fd416b298e03f5aa8124d33011996924cf9831179fd8d26d2fb59727ce840f985edbb

Expected downloaded file to have size: 172473779
Computed size: 172636939

----------

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 4.7.0
25h
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: The process '/usr/bin/yarn' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1179:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1162:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:1062:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
##[error]The process '/usr/bin/yarn' failed with exit code 1
```

This is with Node dependencies:
* @testing-library/cypress: ^6.0.0
* cypress: 4.8.0

And Github Action:
* cypress-io/github-action@v1

**Comment by zack-pronto** [comment]
Same issue here. Any help would be much appreciated.

**Comment by jennifer-shehane** [comment]
@sazzer We often see this error when working with yarn workspaces, where there end up being 2 versions of Cypress inadvertently downloaded. See https://github.com/cypress-io/cypress/issues/4595 for more detail.

**Comment by sazzer** [comment]
@jennifer-shehane  That's fair enough, but this is a clean build with only a single module that only has a single Cypress dependency. I'm assuming - though don't know for sure! - that the Github Action step I'm depending on itself is somehow pulling in Cypress 4.7.0, and that means I can't myself use 4.8.0.

**Comment by zack-pronto** [comment]
My project isn't using yarn workspaces either. It's a single module.
