### ISSUE TITLE
Start command does not work on Windows

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#17]
`start: npm start` does not work on windows :(

```
starting server with command "npm start"
current working directory "d:\a\cypress-example-kitchensink\cypress-example-kitchensink"
child process unref
Running Cypress tests
Cypress test command: npx cypress run --record --parallel --ci-build-id "Using Cypress GH Action - 52315829bed30d850a34a2d775c9a3400a93bff3" --group "Parallel 2x on windows-latest"
C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npx.cmd" cypress run --record --parallel --ci-build-id """Using Cypress GH Action - 52315829bed30d850a34a2d775c9a3400a93bff3""" --group """Parallel 2x on windows-latest""""
(node:2276) UnhandledPromiseRejectionWarning: Error: spawn npm start ENOENT
    at notFoundError (d:\a\_actions\cypress-io\github-action\22f7a76\dist\index.js:6400:26)
    at verifyENOENT (d:\a\_actions\cypress-io\github-action\22f7a76\dist\index.js:6434:16)
    at ChildProcess.cp.emit (d:\a\_actions\cypress-io\github-action\22f7a76\dist\index.js:6421:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
(node:2276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bahmutov** [comment]
worked around it

**Comment by bahmutov** [comment]
also related https://github.com/actions/toolkit/issues/216
