### ISSUE TITLE
Tests fail with "Error: Could not find Cypress test run results" only on CI

### ISSUE THREAD

**Issue by joonashak** [cypress-io/github-action#201]
My previously working CI configuration suddenly stopped working. This action fails with the message `Error: Could not find Cypress test run results`. The tests pass locally (cannot tell if they pass in CI as the logging is halted before the results). I'm wondering if this could be a problem with `cypress-io/github-action`?

The project and branch in question is this: https://github.com/joonashak/reclab-web/tree/trunk

And here is the output from the action after Gatsby has started:

```
  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.12.1                                                                             │
  │ Browser:    Electron 80 (headless)                                                             │
  │ Specs:      1 found (test.spec.js)                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  test.spec.js                                                                    (1 of 1)
Test run failed, code 1
Warning: We failed to record the video.
Could not find Cypress test run results

This error will not alter the exit code.

Error: ffmpeg was killed with signal SIGSEGV
    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

Error: ffmpeg was killed with signal SIGSEGV
    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

Error: ffmpeg was killed with signal SIGSEGV
    at ChildProcess.<anonymous> (/home/runner/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

Error: Could not find Cypress test run results
    at onTestsFinished (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:6166:9)
    at tryCatcher (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/promise.js:673:18)
    at /home/runner/work/reclab-web/reclab-web/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/runner/work/reclab-web/reclab-web/node_modules/jsonfile/index.js:39:16
    at /home/runner/work/reclab-web/reclab-web/node_modules/graceful-fs/graceful-fs.js:123:16
Error: Could not find Cypress test run results
```

Any help would be greatly appreciated, and have a happy Hacktoberfest! ;)

**Comment by joonashak** [comment]
Tried re-running the tests on an earlier commit that had passed and now it failed with the same error as above. Any idea if there has been a breaking change in the action of if this is Github's issue?

**Comment by bahmutov** [comment]
@joonashak can you try using the latest github-action and Cypress please? Wonder if the crash is still present.

**Comment by bahmutov** [comment]
closing without additional information

**Comment by HartiganHM** [comment]
Hey, @bahmutov, I'm having this exact same issue. Tests suddenly started failing in all of our GH Action workflows. I started a GH Discussions [here](https://github.com/cypress-io/cypress/discussions/15441), but haven't received any responses yet and have an open bug ticket [here](https://github.com/featherweight-design/component-library/issues/101). Would you prefer to keep track with this existing issue or open a new one?

Also, to fill in some initial questions, the failing workflows are running Cypress `6.4.0`, but I've also tried updating to `6.6.0` and am still seeing the error. We're running the latest GH Action for Cypress as well, `cypress-io/github-action@v2`.

Thanks for the help!

**Comment by HartiganHM** [comment]
Hey, @bahmutov, just following up with some updates. We're no longer seeing tests omitted from the Cypress Dashboard (which was the case late last week) and are now seeing them time out instead. However, we have almost all of our test results failing in the GH Action pipeline now whereas last it was approximately half failing, half passing. Resources below for you to take a look at. Thanks for the help!

- [Cypress Dashboard run with time outs](https://dashboard.cypress.io/projects/8cgbjw/runs/83/overview)
- [Corresponding GH Action failure](https://github.com/featherweight-design/component-library/actions/runs/656874755)

**Comment by darwin-luque** [comment]
I was having the exact same issue, I solved it by turning off video recording in the cypress.json.
    `{
        ...,
        "video": false,
        ...
    }`

**Comment by HartiganHM** [comment]
Thanks for the suggestion, @darwin-luque. I'll give that a shot later today and report back. Ideally we would still like to see video recordings in the Cypress Dashboard, especially for failures.
