### ISSUE TITLE
Timeout awaiting 'request' for 30000ms

### ISSUE THREAD

**Issue by m1yon** [cypress-io/github-action#286]
Our create-react-app takes awhile to start up as it's grown, and we're now frequently running into this error in our github-action.

```
> clinical-dashboard@0.1.0 start /home/runner/work/clinical-dashboard-v2/clinical-dashboard-v2
> craco start

ℹ ｢wds｣: Project is running at http://10.1.0.4/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /home/runner/work/clinical-dashboard-v2/clinical-dashboard-v2/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

http://localhost:3000 timed out on retry 7 of 2
Error: Timeout awaiting 'request' for 30000ms
```

**This is what our action looks like:**
```
name: Jest and Cypress tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm test
      - name: Increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
```

**What we've tried:**
- changing the wait-on-timeout in the action
- setting pageLoadTimeout in cypress.json
- setting requestTimeout in cypress.json
- setting responseTimeout in cypress.json
- manually setting the timeout in our cy.visit call

**Comment by bahmutov** [comment]
Could you show the debug output from wait retries? https://github.com/cypress-io/github-action#debugging

**Comment by m1yon** [comment]
> Could you show the debug output from wait retries? https://github.com/cypress-io/github-action#debugging

Sorry for the late reply, here's the full output:

##[debug]Evaluating condition for step: 'Cypress run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Cypress run
##[debug]Loading inputs
##[debug]Loading env
Run cypress-io/github-action@v2
##[debug]working directory /home/runner/work/ADDI/ADDI
##[debug]using custom Cypress cache folder "/home/runner/.cache/Cypress"
##[debug]trying to restore cached NPM modules
##[debug]Hash from file /home/runner/work/ADDI/ADDI/package-lock.json is f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c
##[debug]Resolved Keys:
##[debug]["npm-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c","npm-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c"]
##[debug]Checking zstd --version
##[debug]trying to restore cached Cypress binary
##[debug]Hash from file /home/runner/work/ADDI/ADDI/package-lock.json is f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c
##[debug]Resolved Keys:
##[debug]["cypress-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c","cypress-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c"]
##[debug]Checking zstd --version
##[debug]*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/5fAParrsSJEAbnQej4VIVHxXhAqU5ErQMMl4hb0gfRukGmZHOV/_apis/artifactcache/cache?keys=npm-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c%2Cnpm-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c&version=04d00cc68e25ee34fd8b04095d0a46a28244d98af53e6925e47ed311d487b1d6
##[debug]*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/5fAParrsSJEAbnQej4VIVHxXhAqU5ErQMMl4hb0gfRukGmZHOV/_apis/artifactcache/cache?keys=cypress-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c%2Ccypress-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c&version=1955096f8dd018efdf62615d0a27779c95e9b0287a6a71bc182356f3b1a36196
::add-mask::***
##[debug]Cache Result:
##[debug]{"scope":"refs/heads/master","cacheKey":"cypress-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c","cacheVersion":"1955096f8dd018efdf62615d0a27779c95e9b0287a6a71bc182356f3b1a36196","creationTime":"2021-02-11T16:44:32.0433333Z","archiveLocation":"***"}
##[debug]Archive Path: /home/runner/work/_temp/29ce1cba-769e-428f-af61-f4a4e11dc6bf/cache.tzst
##[debug]Use Azure SDK: true
##[debug]Download concurrency: 8
##[debug]Request timeout (ms): 30000
::add-mask::***
##[debug]Cache Result:
##[debug]{"scope":"refs/heads/master","cacheKey":"npm-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c","cacheVersion":"04d00cc68e25ee34fd8b04095d0a46a28244d98af53e6925e47ed311d487b1d6","creationTime":"2021-02-11T16:44:26.9833333Z","archiveLocation":"***"}
##[debug]Archive Path: /home/runner/work/_temp/2565bcbe-f84b-4318-8eef-66fe4395ef2c/cache.tzst
##[debug]Use Azure SDK: true
##[debug]Download concurrency: 8
##[debug]Request timeout (ms): 30000
##[debug]Downloading segment at offset 0 with length 174939422...
##[debug]Downloading segment at offset 0 with length 103486303...
Received 4194304 of 174939422 (2.4%), 4.0 MBs/sec
Received 0 of 103486303 (0.0%), 0.0 MBs/sec
Received 67108864 of 174939422 (38.4%), 32.0 MBs/sec
Received 71303168 of 103486303 (68.9%), 34.0 MBs/sec
Received 103486303 of 103486303 (100.0%), 42.5 MBs/sec
Cache Size: ~99 MB (103486303 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/2565bcbe-f84b-4318-8eef-66fe4395ef2c/cache.tzst -P -C /home/runner/work/ADDI/ADDI
Received 159383552 of 174939422 (91.1%), 50.6 MBs/sec
Received 174939422 of 174939422 (100.0%), 44.1 MBs/sec
Cache Size: ~167 MB (174939422 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/29ce1cba-769e-428f-af61-f4a4e11dc6bf/cache.tzst -P -C /home/runner/work/ADDI/ADDI
##[debug]npm cache hit npm-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c
##[debug]cypress cache hit cypress-linux-x64-f160e2a9f3e4215886f1476f8608ee43c249d2242f3d8a605d7c587c5987292a5ceaf13e16bafc1a937242c8c0318f1f8d1ad5682d806da9108828b7879e002c
##[debug]installing NPM dependencies
##[debug]npm at "/opt/hostedtoolcache/volta/1.0.1/x64/bin/npm"
/opt/hostedtoolcache/volta/1.0.1/x64/bin/npm ci

> core-js-pure@3.7.0 postinstall /home/runner/work/ADDI/ADDI/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.12 postinstall /home/runner/work/ADDI/ADDI/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /home/runner/work/ADDI/ADDI/node_modules/ejs
> node ./postinstall.js


> fsevents@1.2.13 install /home/runner/work/ADDI/ADDI/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported

> fsevents@1.2.13 install /home/runner/work/ADDI/ADDI/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js


Skipping 'fsevents' build as platform linux is not supported

> core-js@3.8.3 postinstall /home/runner/work/ADDI/ADDI/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> husky@4.3.0 install /home/runner/work/ADDI/ADDI/node_modules/husky
> node husky install

husky > Setting up git hooks
CI detected, skipping Git hooks installation.
husky > Done

> husky@4.3.0 postinstall /home/runner/work/ADDI/ADDI/node_modules/husky
> opencollective-postinstall || exit 0


> cypress@6.3.0 postinstall /home/runner/work/ADDI/ADDI/node_modules/cypress
> node index.js --exec install

2021-02-15T21:28:25.435Z cypress:cli installing Cypress from NPM
2021-02-15T21:28:25.660Z cypress:cli installing with options {}
2021-02-15T21:28:25.661Z cypress:cli version in package.json is 6.3.0
2021-02-15T21:28:25.661Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.661Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
Note: Overriding Cypress cache directory to: /home/runner/.cache/Cypress

      Previous installs of Cypress may not be found.

2021-02-15T21:28:25.663Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.663Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.663Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /home/runner/.cache/Cypress
2021-02-15T21:28:25.664Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.664Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.664Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /home/runner/.cache/Cypress
2021-02-15T21:28:25.664Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.664Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:25.665Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /home/runner/.cache/Cypress
2021-02-15T21:28:25.668Z cypress:cli Reading binary package.json from: /home/runner/.cache/Cypress/6.3.0/Cypress/resources/app/package.json
2021-02-15T21:28:25.670Z cypress:cli found npm argv json '{"remain":[],"cooked":["ci"],"original":["ci"]}'
2021-02-15T21:28:25.672Z cypress:cli looking for versionSpecifier { dir: '/home/runner/work/ADDI/ADDI/node_modules/cypress' }
2021-02-15T21:28:25.676Z cypress:cli looking for versionSpecifier { dir: '/home/runner/work/ADDI/ADDI/node_modules' }
2021-02-15T21:28:25.677Z cypress:cli looking for versionSpecifier { dir: '/home/runner/work/ADDI/ADDI' }
2021-02-15T21:28:25.679Z cypress:cli finished looking for versionSpecifier { versionSpecifier: '^6.3.0' }
2021-02-15T21:28:25.681Z cypress:cli installed version is 6.3.0 version needed is 6.3.0

Cypress 6.3.0 is installed in /home/runner/.cache/Cypress/6.3.0

2021-02-15T21:28:25.682Z cypress:cli Not downloading or installing binary
added 2687 packages in 31.048s
##[debug]Cypress versions in the cache folder /home/runner/.cache/Cypress
/opt/hostedtoolcache/volta/1.0.1/x64/bin/npx cypress cache list
2021-02-15T21:28:26.086Z cypress:cli:cli cli starts with arguments ["/opt/hostedtoolcache/volta/1.0.1/x64/tools/image/node/14.15.1/bin/node","/home/runner/work/ADDI/ADDI/node_modules/.bin/cypress","cache","list"]
2021-02-15T21:28:26.087Z cypress:cli NODE_OPTIONS is not set
2021-02-15T21:28:26.087Z cypress:cli:cli program parsing arguments
2021-02-15T21:28:26.090Z cypress:cli:cli cache command { command: 'list', size: undefined }
2021-02-15T21:28:26.091Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:26.091Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:26.091Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /home/runner/.cache/Cypress
2021-02-15T21:28:26.097Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:26.097Z cypress:cli Using CYPRESS_CACHE_FOLDER from environment variable
2021-02-15T21:28:26.098Z cypress:cli using environment variable CYPRESS_CACHE_FOLDER /home/runner/.cache/Cypress
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 6.3.0   │ a few seconds ago │
└─────────┴───────────────────┘
##[debug]no need to verify Cypress binary or save caches
##[debug]Separated start commands npm start
start server "npm start command "npm start"
current working directory "/home/runner/work/ADDI/ADDI"
##[debug]parsed command: npm start
waiting on "http://localhost:3000" with timeout of 120 seconds
##[debug]Waiting for urls http://localhost:3000
##[debug]Waiting for url http://localhost:3000
##[debug]total ping timeout 120000
##[debug]individual ping timeout 30000ms
##[debug]retries limit 4
##[debug]found command "/opt/hostedtoolcache/volta/1.0.1/x64/bin/npm"
##[debug]with arguments start
##[debug]running "/opt/hostedtoolcache/volta/1.0.1/x64/bin/npm" start in /home/runner/work/ADDI/ADDI
##[debug]without waiting for the promise to resolve
##[debug]got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1613424506135,"socket":1613424506137,"lookup":1613424506138,"error":1613424506140,"phases":{"wait":2,"dns":1,"total":5}}}
##[debug]19ms undefined undefined ECONNREFUSED attempt 1
/opt/hostedtoolcache/volta/1.0.1/x64/bin/npm start

> clinical-dashboard@0.1.0 start /home/runner/work/ADDI/ADDI
> craco start

##[debug]got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1613424507148,"socket":1613424507148,"lookup":1613424507149,"error":1613424507149,"phases":{"wait":0,"dns":1,"total":1}}}
##[debug]1021ms undefined undefined ECONNREFUSED attempt 2
##[debug]got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1613424508152,"socket":1613424508152,"lookup":1613424508152,"error":1613424508152,"phases":{"wait":0,"dns":0,"total":0}}}
##[debug]2025ms undefined undefined ECONNREFUSED attempt 3
##[debug]got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1613424509155,"socket":1613424509155,"lookup":1613424509155,"error":1613424509155,"phases":{"wait":0,"dns":0,"total":0}}}
##[debug]3028ms undefined undefined ECONNREFUSED attempt 4
##[debug]got error {"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1613424510158,"socket":1613424510158,"lookup":1613424510158,"error":1613424510158,"phases":{"wait":0,"dns":0,"total":0}}}
##[debug]4031ms undefined undefined ECONNREFUSED attempt 5
ℹ ｢wds｣: Project is running at http://10.1.0.4/
ℹ ｢wds｣: webpack output is served from 
ℹ ｢wds｣: Content not from webpack is served from /home/runner/work/ADDI/ADDI/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1613424511160,"socket":1613424511160,"lookup":1613424511160,"connect":1613424511161,"upload":1613424511161,"error":1613424541163,"phases":{"wait":0,"dns":0,"tcp":1,"request":0,"total":30003}},"event":"request"}
##[debug]35036ms undefined undefined ETIMEDOUT attempt 6
##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1613424571192,"socket":1613424571192,"lookup":1613424571192,"connect":1613424571192,"upload":1613424571192,"error":1613424601219,"phases":{"wait":0,"dns":0,"tcp":0,"request":0,"total":30027}},"event":"request"}
##[debug]95091ms undefined undefined ETIMEDOUT attempt 7
##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1613424631231,"socket":1613424631232,"lookup":1613424631232,"connect":1613424631232,"upload":1613424631232,"error":1613424661239,"phases":{"wait":1,"dns":0,"tcp":0,"request":0,"total":30008}},"event":"request"}
http://localhost:3000 timed out on retry 8 of 4
##[debug]155111ms undefined undefined ETIMEDOUT attempt 8
##[debug]Timeout awaiting 'request' for 30000ms
##[debug]RequestError: Timeout awaiting 'request' for 30000ms
##[debug]    at ClientRequest.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:3544:65)
##[debug]    at Object.onceWrapper (events.js:300:26)
##[debug]    at ClientRequest.emit (events.js:215:7)
##[debug]    at ClientRequest.origin.emit (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:59972:20)
##[debug]    at Socket.socketErrorListener (_http_client.js:406:9)
##[debug]    at Socket.emit (events.js:210:5)
##[debug]    at emitErrorNT (internal/streams/destroy.js:92:8)
##[debug]    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
##[debug]    at processTicksAndRejections (internal/process/task_queues.js:80:21)
##[debug]    at Timeout.timeoutHandler [as _onTimeout] (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:77948:25)
##[debug]    at listOnTimeout (internal/timers.js:533:17)
##[debug]    at processTimers (internal/timers.js:475:7)
Error: Timeout awaiting 'request' for 30000ms
##[debug]Node Action run completed with exit code 1
##[debug]CI='1'
##[debug]CYPRESS_CACHE_FOLDER='/home/runner/.cache/Cypress'
##[debug]npm_config_cache='/home/runner/.npm'
##[debug]CYPRESS_CACHE_FOLDER='/home/runner/.cache/Cypress'
##[debug]Finishing: Cypress run

**Comment by bahmutov** [comment]
Can you increase the timeout limit?

**Comment by m1yon** [comment]
> Can you increase the timeout limit?

the wait-on-timeout?

I can't seem to find the variable that
> ##[debug]Request timeout (ms): 30000

is actually tied to. No matter what config we change in the action or cypress, it seems to be 30000ms here in the action.

**Comment by NorbertoStudios** [comment]
any luck ? im having the same issue

**Comment by m1yon** [comment]
> any luck ? im having the same issue

Unfortunately I couldn't get the action to work, but I was able to get it working with the `start-server-and-test` library recommended in the [Cypress CI Guide](https://docs.cypress.io/guides/continuous-integration/introduction.html#Boot-your-server):

```json
{
  "scripts": {
    "start": "my-server -p 3030",
    "cy:run": "cypress run",
    "test": "start-server-and-test start http://localhost:3030 cy:run"
  }
}
```

start-server-and-test has a 5 minute timeout by default.

**Comment by bahmutov** [comment]
Ok, I could recreate the error in https://github.com/cypress-io/github-action/tree/add-wait-timeout-longer-test

https://github.com/cypress-io/github-action/runs/2228821050?check_suite_focus=true

```
/usr/local/bin/npm run start3-after-200-seconds

> example-wait-on@1.0.0 start3-after-200-seconds /home/runner/work/github-action/github-action/examples/wait-on
> node ./index3 --delay 200

2021-03-30T14:57:30.487Z * creating the server on port 3050
2021-03-30T14:57:30.488Z * will not respond for the first 200 seconds
2021-03-30T14:57:30.492Z * server is listening
2021-03-30T14:57:31.230Z * request GET /
2021-03-30T14:57:31.230Z * not responding
##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1617116251226,"socket":1617116251227,"lookup":1617116251227,"connect":1617116251227,"upload":1617116251227,"error":1617116281228,"phases":{"wait":1,"dns":0,"tcp":0,"request":0,"total":30002}},"event":"request"}
##[debug]31020ms undefined undefined ETIMEDOUT attempt 2
2021-03-30T14:58:31.237Z * request GET /
2021-03-30T14:58:31.238Z * not responding
##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1617116311236,"socket":1617116311236,"lookup":1617116311236,"connect":1617116311236,"upload":1617116311236,"error":1617116341263,"phases":{"wait":0,"dns":0,"tcp":0,"request":0,"total":30027}},"event":"request"}
##[debug]91054ms undefined undefined ETIMEDOUT attempt 3
2021-03-30T14:59:31.296Z * request GET /
2021-03-30T14:59:31.296Z * not responding
##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1617116371295,"socket":1617116371295,"lookup":1617116371295,"connect":1617116371296,"upload":1617116371296,"error":1617116401326,"phases":{"wait":0,"dns":0,"tcp":1,"request":0,"total":30031}},"event":"request"}
##[debug]151118ms undefined undefined ETIMEDOUT attempt 4
2021-03-30T15:00:31.331Z * request GET /
2021-03-30T15:00:31.331Z * not responding
2021-03-30T15:00:50.508Z * the server will now answer ok
##[debug]got error {"name":"TimeoutError","code":"ETIMEDOUT","timings":{"start":1617116431330,"socket":1617116431330,"lookup":1617116431331,"connect":1617116431331,"upload":1617116431331,"error":1617116461342,"phases":{"wait":0,"dns":1,"tcp":0,"request":0,"total":30012}},"event":"request"}
##[debug]211133ms undefined undefined ETIMEDOUT attempt 5
http://localhost:3050 timed out on retry 5 of 7
##[debug]Timeout awaiting 'request' for 30000ms
##[debug]RequestError: Timeout awaiting 'request' for 30000ms
##[debug]    at ClientRequest.<anonymous> (/home/runner/work/github-action/github-action/dist/index.js:5854:65)
##[debug]    at Object.onceWrapper (events.js:300:26)
```

**Comment by bahmutov** [comment]
Very weird, see a difference in behavior between the Linux CI and local Mac (where everything works as expected)

**Comment by dartamonov-vertex** [comment]
I'm experiencing the same issue on 2.9.7.
My action setup:
`        uses: cypress-io/github-action@v2.9.7
        with:
          wait-on: 'https://localhost:9001'
          start: npm run start:test
          command: npm run cypress:run:test
          install: false
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0`

Error log:
`Run cypress-io/github-action@v2.9.7
Skipping install because install parameter is false
start server "npm run start:test command "npm run start:test"
current working directory "/home/runner/work/vtx-ui-react-scripts/vtx-ui-react-scripts/vtx-ui-mf-test/cypress"
waiting on "https://localhost:9001" with timeout of 60 seconds
(node:2242) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
/opt/hostedtoolcache/node/12.22.0/x64/bin/npm run start:test

｢wds｣: Generating SSL Certificate
｢wds｣: Project is running at https://localhost:9001/
｢wds｣: webpack output is served from /
｢wds｣: Content not from webpack is served from /home/runner/work/vtx-ui-react-scripts/vtx-ui-react-scripts/vtx-ui-mf-test
｢wds｣: 404s will fallback to /index.html
WebpackDevServer listening at localhost: 9001

Time: 4030ms
https://localhost:9001 timed out on retry 6 of 3, elapsed 94655ms, limit 90000ms
Error: Response code 404 (Not Found)`
