### ISSUE TITLE
Check how caching works with Windows

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/github-action#3]
See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

`windows-latest` for Windows Server 2019

**Comment by bahmutov** [comment]
Hmm, `yarn` is unavailable on Node 12 on Windows?

**Comment by bahmutov** [comment]
Hmm, even `npm ci` is not working, need to probably use toolkit IO to find NPM and yarn

```
npm cache hit false
cypress cache hit false
installing NPM dependencies
npm ci
Error: There was an error when attempting to execute the process 'npm'. This may indicate the process failed to start. Error: spawn npm ENOENT
    at ExecState._setResult (d:\a\_actions\cypress-io\github-action\v1\dist\index.js:891:25)
    at ExecState.CheckComplete (d:\a\_actions\cypress-io\github-action\v1\dist\index.js:877:18)
    at ChildProcess.<anonymous> (d:\a\_actions\cypress-io\github-action\v1\dist\index.js:764:27)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
##[error]There was an error when attempting to execute the process 'npm'. This may indicate the process failed to start. Error: spawn npm ENOENT
##[error]Node run failed with exit code 1
```

**Comment by bahmutov** [comment]
Using project https://github.com/bahmutov/yarn-cypress-cache as a test ground
