### ISSUE TITLE
Need Help, Error when run test 

### ISSUE THREAD

**Issue by udahari** [cypress-io/github-action#39]
```Cypress test command: npx cypress run --config-file cypress.json --env false
/usr/local/bin/npx cypress run --config-file cypress.json --env false

Error: There was an error when attempting to execute the process '/usr/local/bin/npx'. This may indicate the process failed to start. Error: spawn /usr/local/bin/npx ENOENT
    at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:891:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:877:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:764:27)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
##[error]There was an error when attempting to execute the process '/usr/local/bin/npx'. This may indicate the process failed to start. Error: spawn /usr/local/bin/npx ENOENT
##[error]Node run failed with exit code 1```

**Comment by bahmutov** [comment]
hmm, do you use custom environment or runner without Node? What version of node are you running there?

**Comment by bahmutov** [comment]
Closing because of no details provided
