### ISSUE TITLE
PNMP support

### ISSUE THREAD

**Issue by BryceBarbara** [cypress-io/github-action#438]
Howdy!

I've been trying to get this running on a private repo and quickly ran into the issue that the system only has support for specific package managers. It'd be nice to be able to provide custom commands to add support for PNMP or to have built-in support if that's easier

**Comment by kitsune7** [comment]
☝🏻 I was a bit surprised by that this doesn't seem to work with pnpm. I get the following error (though I'm removing parts of the directory names in the message):

```
Run cypress-io/github-action@v2
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/work/--REPO--/--REPO--/package-lock.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Function.module.exports.hasha.fromFileSync (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:18048:54)
    at lockHash (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:6729:26)
    at getNpmCache (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:6739:16)
    at restoreCachedNpm (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:6784:21)
    at installMaybe (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:7365:5)
    at Object.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:7388:1)
    at __webpack_require__ (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:43:19) ***
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/work/--REPO--/--REPO--/package-lock.json'
***
```

I removed `package-lock.json` because it was only used by npm, but it seems like there's still a dependency on it here. None of the other code in my workflow makes any reference to `package-lock.json`.

**Comment by kitsune7** [comment]
Now that I've looked into this a little more, it seems like this is a duplicate issue. The solution I found from issue [145](https://github.com/cypress-io/github-action/issues/145) is to add `install: false` to the `with` property in my workflow.

**Comment by BryceBarbara** [comment]
@kitsune7 I think you're right! I'll close this one.
