### ISSUE TITLE
Parsing error when adding userAgent to config

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/github-action#442]
This is my workflow file:
https://github.com/uoForms/App-CANBeWell/blob/b3299f0a9674bfc74b7fc6f73c8864eea2e81a0b/.github/workflows/ci-build-cy-test-text-locale-ios.yml

I have `config: userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

This is the error log with debug on:
https://github.com/uoForms/App-CANBeWell/pull/444/checks?check_run_id=3923077727

```
2021-10-18T06:22:47.451Z @cypress/github-action pinging http://localhost:3000 has finished ok after 21585ms
2021-10-18T06:22:47.453Z @cypress/github-action Running Cypress tests using NPM module API
2021-10-18T06:22:47.453Z @cypress/github-action requiring cypress dependency, cwd is /home/runner/work/App-CANBeWell/App-CANBeWell
2021-10-18T06:22:47.454Z @cypress/github-action working directory /home/runner/work/App-CANBeWell/App-CANBeWell
2021-10-18T06:22:47.456Z @cypress/github-action resolved cypress /home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/cypress/index.js
2021-10-18T06:22:47.793Z @cypress/github-action Cypress config "userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"
2021-10-18T06:22:47.793Z @cypress/github-action extracted spec lines into: "cypress/integration/textLocaleTests/testSet/ios-add-to-home-screen.js"
2021-10-18T06:22:47.793Z @cypress/github-action Cypress options {"headless":false,"record":false,"parallel":false,"quiet":false,"config":"userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148","spec":"cypress/integration/textLocaleTests/testSet/ios-add-to-home-screen.js","configFile":"cypress/configs/ci-build.json","browser":"chrome"}
Cypress encountered an error while parsing the argument config

You passed: userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

The error was: Cannot read property 'split' of undefined
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
2021-10-18T06:22:54.902Z @cypress/github-action Could not find Cypress test run results
2021-10-18T06:22:54.902Z @cypress/github-action Error: Could not find Cypress test run results
Error: Could not find Cypress test run results
    at onTestsFinished (/home/runner/work/_actions/cypress-io/github-action/v2/dist/index.js:7322:9)
    at tryCatcher (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/promise.js:673:18)
    at /home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/runner/work/App-CANBeWell/App-CANBeWell/node_modules/cypress/node_modules/universalify/index.js:22:54
```

**Comment by MikeMcC399** [comment]
@Songyu-Wang 

> `config: userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

This is an incorrect usage of the parameter [config](https://github.com/cypress-io/github-action#config).

You would need to set the parameter `userAgent` in the github-action  [config](https://github.com/cypress-io/github-action#config) parameter.
