### ISSUE TITLE
Is this action missing some required dependency for Cypress 3.8.2?

### ISSUE THREAD

**Issue by lourenci** [cypress-io/github-action#65]
I'm getting the ["This is usually caused by a missing library or dependency."](https://github.com/lourenci/react-kanban/runs/401989842) error after upgrading Cypress to 3.8.2. 

Is this action not supporting the new Cypress versions?

Thanks

**Comment by prescottprue** [comment]
I am also receiving this:

![image](https://user-images.githubusercontent.com/2992224/72857197-c27a7e00-3c71-11ea-9643-135c8a3900ed.png)

I had been running 3.8.2 with things working, but this issue appeared today and hasn't gone away after many retries

**Comment by jennifer-shehane** [comment]
Could you run `cypress verify` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

**Comment by joshiste** [comment]
Also happens on for cypress 3.7.0 

```
2020-01-22T09:02:06.4045023Z > cypress@3.7.0 postinstall /home/runner/work/integration-tests/integration-tests/node_modules/cypress
2020-01-22T09:02:06.4045809Z > node index.js --exec install
2020-01-22T09:02:06.4046181Z 
2020-01-22T09:02:06.8537294Z Note: Overriding Cypress cache directory to: /home/runner/.cache/Cypress
2020-01-22T09:02:06.8537909Z 
2020-01-22T09:02:06.8538304Z       Previous installs of Cypress may not be found.
2020-01-22T09:02:06.8541706Z 
2020-01-22T09:02:06.8690879Z Installing Cypress (version: 3.7.0)
2020-01-22T09:02:06.8691312Z 
2020-01-22T09:02:06.8747582Z [?25l[09:02:06]  Downloading Cypress     [started]
2020-01-22T09:02:08.8600985Z [09:02:08]  Downloading Cypress     [completed]
2020-01-22T09:02:08.8611976Z [09:02:08]  Unzipping Cypress       [started]
2020-01-22T09:02:58.4964445Z [09:02:58]  Unzipping Cypress       [completed]
2020-01-22T09:02:58.4972486Z [09:02:58]  Finishing Installation  [started]
2020-01-22T09:02:58.6797214Z [09:02:58]  Finishing Installation  [completed]
2020-01-22T09:02:59.6819482Z [?25h
2020-01-22T09:02:59.6821381Z You can now open Cypress by running: node_modules/.bin/cypress open
2020-01-22T09:02:59.6821883Z 
2020-01-22T09:02:59.6822606Z https://on.cypress.io/installing-cypress
2020-01-22T09:02:59.6822738Z 
2020-01-22T09:02:59.7028940Z [?25h
2020-01-22T09:02:59.7029864Z > core-js@2.6.10 postinstall /home/runner/work/integration-tests/integration-tests/node_modules/core-js
2020-01-22T09:02:59.7030531Z > node postinstall || echo "ignore"
2020-01-22T09:02:59.7030853Z 
2020-01-22T09:02:59.8066683Z added 245 packages in 57.786s
2020-01-22T09:02:59.8158358Z [command]/usr/local/bin/npx cypress verify
2020-01-22T09:03:00.1640278Z It looks like this is your first time using Cypress: 3.7.0
2020-01-22T09:03:00.1647481Z 
2020-01-22T09:03:00.1693733Z [?25l[09:03:00]  Verifying Cypress can run /home/runner/.cache/Cypress/3.7.0/Cypress [started]
2020-01-22T09:03:08.2469362Z [09:03:08]  Verifying Cypress can run /home/runner/.cache/Cypress/3.7.0/Cypress [failed]
2020-01-22T09:03:08.2477346Z [?25hCypress failed to start.
2020-01-22T09:03:08.2477687Z 
2020-01-22T09:03:08.2477936Z This is usually caused by a missing library or dependency.
2020-01-22T09:03:08.2478021Z 
2020-01-22T09:03:08.2478212Z The error below should indicate which dependency is missing.
2020-01-22T09:03:08.2478312Z 
2020-01-22T09:03:08.2479643Z https://on.cypress.io/required-dependencies
2020-01-22T09:03:08.2479754Z 
2020-01-22T09:03:08.2479902Z If you are using Docker, we provide containers with all required dependencies installed.
2020-01-22T09:03:08.2480012Z 
2020-01-22T09:03:08.2480384Z ----------
2020-01-22T09:03:08.2480452Z 
2020-01-22T09:03:08.2480872Z Command failed: /home/runner/.cache/Cypress/3.7.0/Cypress/Cypress --no-sandbox --smoke-test --ping=852
2020-01-22T09:03:08.2481176Z 
2020-01-22T09:03:08.2481503Z ----------
2020-01-22T09:03:08.2481587Z 
2020-01-22T09:03:08.2481907Z Platform: linux (Ubuntu Linux - 18.04)
2020-01-22T09:03:08.2482042Z Cypress Version: 3.7.0
2020-01-22T09:03:08.2553177Z [?25hError: The process '/usr/local/bin/npx' failed with exit code 1
2020-01-22T09:03:08.2554085Z     at ExecState._setResult (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:894:25)
2020-01-22T09:03:08.2556998Z     at ExecState.CheckComplete (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:877:18)
2020-01-22T09:03:08.2557856Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/cypress-io/github-action/v1/dist/index.js:777:27)
2020-01-22T09:03:08.2558308Z     at ChildProcess.emit (events.js:210:5)
2020-01-22T09:03:08.2558661Z     at maybeClose (internal/child_process.js:1021:16)
2020-01-22T09:03:08.2559016Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-01-22T09:03:08.2561785Z ##[error]The process '/usr/local/bin/npx' failed with exit code 1
2020-01-22T09:03:08.2586830Z ##[error]Node run failed with exit code 1
2020-01-22T09:03:08.2708796Z ##[group]Run actions/upload-artifact@v1
2020-01-22T09:03:08.2708969Z with:
2020-01-22T09:03:08.2709467Z   name: cypress-screenshots
2020-01-22T09:03:08.2709611Z   path: cypress/screenshots
2020-01-22T09:03:08.2709739Z env:
2020-01-22T09:03:08.2709864Z   CI: 1
2020-01-22T09:03:08.2709999Z   CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
2020-01-22T09:03:08.2710145Z   npm_config_cache: /home/runner/.npm
2020-01-22T09:03:08.2710288Z ##[endgroup]
2020-01-22T09:03:08.5055698Z ##[error]Path does not exist /home/runner/work/integration-tests/integration-tests/cypress/screenshots
2020-01-22T09:03:08.5419112Z ##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.164.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
2020-01-22T09:03:08.5590047Z ##[group]Run actions/upload-artifact@v1
2020-01-22T09:03:08.5590227Z with:
2020-01-22T09:03:08.5590366Z   name: cypress-videos
2020-01-22T09:03:08.5590498Z   path: cypress/videos
2020-01-22T09:03:08.5590626Z env:
2020-01-22T09:03:08.5590752Z   CI: 1
2020-01-22T09:03:08.5590887Z   CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
2020-01-22T09:03:08.5591030Z   npm_config_cache: /home/runner/.npm
2020-01-22T09:03:08.5591160Z ##[endgroup]
2020-01-22T09:03:08.8091282Z ##[error]Path does not exist /home/runner/work/integration-tests/integration-tests/cypress/videos
2020-01-22T09:03:08.8293855Z ##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.164.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Artifact.PublishArtifact, Runner.Plugins"'.
2020-01-22T09:03:08.8415585Z ##[group]Run 8398a7/action-slack@v2
2020-01-22T09:03:08.8415738Z with:
2020-01-22T09:03:08.8415857Z   status: Failure
2020-01-22T09:03:08.8415973Z   author_name: github
2020-01-22T09:03:08.8416087Z   only_mention_fail: here
2020-01-22T09:03:08.8416203Z env:
2020-01-22T09:03:08.8416316Z   CI: 1
2020-01-22T09:03:08.8416421Z   CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
2020-01-22T09:03:08.8416552Z   npm_config_cache: /home/runner/.npm
2020-01-22T09:03:08.8417320Z   GITHUB_TOKEN: ***
2020-01-22T09:03:08.8417566Z   SLACK_WEBHOOK_URL: ***
2020-01-22T09:03:08.8417667Z ##[endgroup]
2020-01-22T09:03:09.1549064Z (node:3204) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-01-22T09:03:09.2686427Z Cleaning up orphan processes
```

**Comment by WouterSioen** [comment]
```
2020-01-22T09:24:50.879Z cypress:cli Smoke test failed: Error: Command failed: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=480


    at makeError (/home/runner/work/htaccess/htaccess/node_modules/cypress/node_modules/execa/index.js:172:9)
    at /home/runner/work/htaccess/htaccess/node_modules/cypress/node_modules/execa/index.js:277:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  code: null,
  stdout: '',
  stderr: '',
  failed: true,
  signal: 'SIGSEGV',
  cmd: '/home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=480',
  timedOut: false,
  killed: false
}
2020-01-22T09:24:50.881Z cypress:cli error message: Command failed: /home/runner/.cache/Cypress/3.8.2/Cypress/Cypress --no-sandbox --smoke-test --ping=480
```

This is the output I get when I enable debug mode when using this GitHub Action.

Worked perfectly fine until some hours ago.

**Comment by marudor** [comment]
It has to do with ubuntu-latest. If you use ubuntu-16.04 it works. (Did github recently change the latest to use 18.04?)

**Comment by csi-lk** [comment]
@marudor correct, looks like `ubuntu-latest` is now `18.04` pinning to `ubuntu-16.04` works fine

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners

**Comment by joshiste** [comment]
Will there be an update to support ubuntu 18.04?

**Comment by lourenci** [comment]
> It has to do with ubuntu-latest. If you use ubuntu-16.04 it works. (Did github recently change the latest to use 18.04?)

Thanks for that, @marudor. I've pinned the action to use that version and it works as expected.

I'll close this action in favor of #66.

**Comment by prescottprue** [comment]
For anyone interested in tracking the exact change causing this, it seems like it may be one of these releases on the actions/virtual-environments repo since the timeline matches up: https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20200119.1. Not exactly sure what Cypress dependency changed, or why a pre-release would be getting pulled, but I have had cypress builds with 18.04 work before the other day.

**Comment by jennifer-shehane** [comment]
There has been an update added to our Readme detailing this issue https://github.com/cypress-io/github-action#important

>We are getting reports that Cypress has suddenly started crashing when running on `ubuntu-latest` OS. Seems, GH Actions have switched from 16.04 to 18.04 overnight, and are having a [xvfb issue](https://github.com/cypress-io/cypress/pull/6199). Please wor around this problem by using `runs-on: ubuntu-16.04` image.
