### ISSUE TITLE
Error: The process '/usr/bin/yarn' failed with exit code 1

### ISSUE THREAD

**Issue by madeeha96** [cypress-io/github-action#797]
Facing: Error: The process '/usr/bin/yarn' failed with exit code 1
on following work flow 

```
name: Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress E2E 🧪
    runs-on: [self-hosted, default]
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    timeout-minutes: 15
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start
          working-directory: ./applications/cui-webapp/app
```

Please guide. Tried checking Yarn check (what yarn) action before cypress run. It returns legit yarn path `/usr/local/bin/yarn`
What can be the issue?

**Comment by MikeMcC399** [comment]
@madeeha96 

If you add 

```
env:
  DEBUG: '@cypress/github-action, cypress:*'
```

to your workflow, you should be able to find more debug information.

There is a section [Debugging](https://github.com/cypress-io/github-action#debugging) in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) documentation which describes this.

**Comment by madeeha96** [comment]
@MikeMcC399 added debugger, attaching logs: 

<img width="1131" alt="Screenshot 2023-02-17 at 08 21 34" src="https://user-images.githubusercontent.com/33419910/219577025-e3fc6456-9ff3-4656-9136-f17b0a73b5ed.png">


Raw logs: 
`2023-02-17T07:17:41.0752036Z   working-directory: ./applications/cui-webapp
2023-02-17T07:17:41.0752285Z   install-command: yarn --frozen-lockfile --silent
2023-02-17T07:17:41.0752490Z   build: yarn app:build
2023-02-17T07:17:41.0752654Z   start: yarn start
2023-02-17T07:17:41.0752808Z   record: false
2023-02-17T07:17:41.0752966Z   component: false
2023-02-17T07:17:41.0753117Z env:
2023-02-17T07:17:41.0753291Z   GITHUB_REPOSITORY_NAME: conversions-ui
2023-02-17T07:17:41.0753487Z   GITHUB_RUN_UID: 4201525477-23-1
2023-02-17T07:17:41.0753837Z   GITHUB_TOKEN: ***
2023-02-17T07:17:41.0754066Z   SONAR_TOKEN: ***
2023-02-17T07:17:41.0754266Z   NPM_TOKEN: ***
2023-02-17T07:17:41.0754450Z   NPM_REGISTRY: ***
2023-02-17T07:17:41.0754648Z   DEBUG: @cypress/github-action, cypress:*
2023-02-17T07:17:41.0754839Z ##[endgroup]
2023-02-17T07:17:41.2238912Z 2023-02-17T07:17:41.223Z @cypress/github-action working directory /runner/_work/conversions-ui/conversions-ui/applications/cui-webapp
2023-02-17T07:17:41.2244344Z 2023-02-17T07:17:41.224Z @cypress/github-action using custom Cypress cache folder "/home/runner/.cache/cypress/12.5.1"
2023-02-17T07:17:41.2245140Z 2023-02-17T07:17:41.224Z @cypress/github-action trying to restore cached NPM modules
2023-02-17T07:17:41.2256773Z 2023-02-17T07:17:41.225Z @cypress/github-action Hash from file /runner/_work/conversions-ui/conversions-ui/applications/cui-webapp/yarn.lock is 05a0efe3b32a8c2628fb2252a5c168b4dd9da860101a31a6d5ab6e638f760d789d174d73c464ff70ca8abfc2e820a07aea1eb22be77e0fe03d88f5dc5229d5ad
2023-02-17T07:17:41.2273369Z 2023-02-17T07:17:41.227Z @cypress/github-action trying to restore cached Cypress binary
2023-02-17T07:17:41.2282698Z 2023-02-17T07:17:41.228Z @cypress/github-action Hash from file /runner/_work/conversions-ui/conversions-ui/applications/cui-webapp/yarn.lock is 05a0efe3b32a8c2628fb2252a5c168b4dd9da860101a31a6d5ab6e638f760d789d174d73c464ff70ca8abfc2e820a07aea1eb22be77e0fe03d88f5dc5229d5ad
2023-02-17T07:17:41.3925561Z 2023-02-17T07:17:41.392Z @cypress/github-action npm cache hit undefined
2023-02-17T07:17:41.3926372Z 2023-02-17T07:17:41.392Z @cypress/github-action cypress cache hit undefined
2023-02-17T07:17:41.3932642Z 2023-02-17T07:17:41.393Z @cypress/github-action using custom install command "yarn --frozen-lockfile --silent"
2023-02-17T07:17:41.3936686Z install command command "yarn --frozen-lockfile --silent"
2023-02-17T07:17:41.3938164Z current working directory "/runner/_work/conversions-ui/conversions-ui/applications/cui-webapp"
2023-02-17T07:17:41.3940570Z 2023-02-17T07:17:41.393Z @cypress/github-action parsed command: yarn --frozen-lockfile --silent
2023-02-17T07:17:41.3948375Z 2023-02-17T07:17:41.394Z @cypress/github-action found command "/usr/bin/yarn"
2023-02-17T07:17:41.3948885Z 2023-02-17T07:17:41.394Z @cypress/github-action with arguments --frozen-lockfile --silent
2023-02-17T07:17:41.3949823Z 2023-02-17T07:17:41.394Z @cypress/github-action running "/usr/bin/yarn" --frozen-lockfile --silent in /runner/_work/conversions-ui/conversions-ui/applications/cui-webapp
2023-02-17T07:17:41.3950422Z 2023-02-17T07:17:41.394Z @cypress/github-action waiting for the command to finish? true
2023-02-17T07:17:41.3952382Z [command]/usr/bin/yarn --frozen-lockfile --silent
2023-02-17T07:17:41.6965006Z [91m➤[39m YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
2023-02-17T07:17:41.7044903Z 2023-02-17T07:17:41.704Z @cypress/github-action The process '/usr/bin/yarn' failed with exit code 1
2023-02-17T07:17:41.7089393Z 2023-02-17T07:17:41.708Z @cypress/github-action Error: The process '/usr/bin/yarn' failed with exit code 1
2023-02-17T07:17:41.7089891Z     at ExecState._setResult (/runner/_work/_actions/cypress-io/github-action/v5/dist/index.js:3773:25)
2023-02-17T07:17:41.7090633Z     at ExecState.CheckComplete (/runner/_work/_actions/cypress-io/github-action/v5/dist/index.js:3756:18)
2023-02-17T07:17:41.7091484Z     at ChildProcess.<anonymous> (/runner/_work/_actions/cypress-io/github-action/v5/dist/index.js:3650:27)
2023-02-17T07:17:41.7091990Z     at ChildProcess.emit (node:events:527:28)
2023-02-17T07:17:41.7092310Z     at maybeClose (node:internal/child_process:1092:16)
2023-02-17T07:17:41.7092773Z     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
2023-02-17T07:17:41.7110248Z ##[error]The process '/usr/bin/yarn' failed with exit code 1
2023-02-17T07:17:41.7164758Z Post job cleanup.
2023-02-17T07:17:41.8082912Z [command]/usr/bin/git version
2023-02-17T07:17:41.8123574Z git version 2.39.1
2023-02-17T07:17:41.8160827Z Temporarily overriding HOME='/runner/_work/_temp/61034860-d173-41e7-872b-e4ba8b83cd51' before making global git config changes
2023-02-17T07:17:41.8161863Z Adding repository directory to the temporary git global config as a safe directory
2023-02-17T07:17:41.8166728Z [command]/usr/bin/git config --global --add safe.directory /runner/_work/conversions-ui/conversions-ui
2023-02-17T07:17:41.8199255Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2023-02-17T07:17:41.8226833Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2023-02-17T07:17:41.8376010Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2023-02-17T07:17:41.8399335Z http.https://github.com/.extraheader
2023-02-17T07:17:41.8407918Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2023-02-17T07:17:41.8435501Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2023-02-17T07:17:41.8645341Z A job completed hook has been configured by the self-hosted runner administrator
2023-02-17T07:17:41.8666695Z ##[group]Run '/etc/arc/hooks/job-completed.sh'
2023-02-17T07:17:41.8679165Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2023-02-17T07:17:41.8679401Z ##[endgroup]
2023-02-17T07:17:41.8719332Z [0;37m2023-02-17 07:17:41.871  DEBUG --- Running ARC Job Completed Hooks[0m
2023-02-17T07:17:41.8729157Z [0;37m2023-02-17 07:17:41.872  DEBUG --- Running hook: /etc/arc/hooks/job-completed.d/update-status[0m
2023-02-17T07:17:41.8858465Z Cleaning up orphan processes`

**Comment by MikeMcC399** [comment]
@madeeha96 

- Which version of yarn are you using?
- What is the operating system of your `runs-on: [self-hosted, default]` selection?

**Comment by MikeMcC399** [comment]
@madeeha96 

Your log file suggest that you are not using yarn v1 (classic):

```text
YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache
```

so I suggest that you add the install command that you need using the parameter `install-command`, for instance:

```yml
        with:
          working-directory: ./applications/cui-webapp/app
          install-command: yarn install
```
That will not solve your exit code problem, but it should get rid of the deprecation message.

Since the yarn command is failing on your runner 

```text
The process '/usr/bin/yarn' failed with exit code 1
```

you could try running `yarn install` by hand on your local copy of the repository. It looks like there is something missing in your yarn setup.

For test purposes you could also add a yml step

```yml
run: yarn install
```

before the step using `cypress-io/github-action@v5`. I would expect that to fail, and to demonstrate that the problem is not coming from `cypress-io/github-action`.

Good luck!

**Comment by madeeha96** [comment]
Thanks, @MikeMcC399 `install-command: yarn install` worked. Also, tried yarn install one step above which required .NPM Registry credentials to install internal packages.

**Comment by MikeMcC399** [comment]
@madeeha96 

It's good to hear that you were able to solve the issue! Thank you for getting back to us here and letting us know also the Yarn version that you are working with.
