### ISSUE TITLE
Runing test on self-hosted runners

### ISSUE THREAD

**Issue by ray31245** [cypress-io/github-action#821]
```
name: Cypress Integration Test

on:
  workflow_dispatch:

jobs: 
  cypress-run: 
    runs-on: self-hosted 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test
      - name: Cypress run
        uses: cypress-io/github-action@v5 
        env: 
          DEBUG: '@cypress/github-action'
        with:
          build: npm run cy:run
```

Above is the work flow. it does not work on self-hosted runner, but on Github-Hosted runner is works well.
follow is the error message.

```
`2023-03-08T16:31:17.446Z @cypress/github-action working directory /home/runner/actions-runner/_work/cypress-ci-test/cypress-ci-test
2023-03-08T16:31:17.450Z @cypress/github-action using custom Cypress cache folder "/home/runner/.cache/Cypress"
2023-03-08T16:31:17.450Z @cypress/github-action trying to restore cached NPM modules
2023-03-08T16:31:17.452Z @cypress/github-action Hash from file /home/runner/actions-runner/_work/cypress-ci-test/cypress-ci-test/package-lock.json is 4404575b8ea298f4a836b139b4fd1f7960e22d65ae030e702555522f3f4727c8a77dcb2e7c3458b0eca604c4df770d15351616694ffc2bf39b16791a914b2
2023-03-08T16:31:17.458Z @cypress/github-action trying to restore cached Cypress binary
2023-03-08T16:31:17.460Z @cypress/github-action Hash from file /home/runner/actions-runner/_work/cypress-ci-test/cypress-ci-test/package-lock.json is 4404575b98ea298f4a836b9b4fd1f7960e22d65ae030e702555522f3f4727c8a77dcb2e7c3458b0eca604c4df770d1535161669411ffc2bf39b16791a9b2
2023-03-08T16:31:18.441Z @cypress/github-action npm cache hit undefined
2023-03-08T16:31:18.441Z @cypress/github-action cypress cache hit undefined
2023-03-08T:31:18.444Z @cypress/github-action installing NPM dependencies
2023-03-08T16:31:18.447Z @cypress/github-action Unable to locate executable file: npm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
2023-03-08T16:31:.463Z @cypress/github-action Error: Unable to locate executable file: npm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
    at Object.<anonymous> (/home/runner/actions-runner/_work/_actions/cypress-io/github-action/v5/dist/index.js:6034:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/actions-runner/_work/_actions/cypress-io/github-action/v5/dist/index.js:5845:58)
Error: Unable to locate executable file: npm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`
```

**Comment by MikeMcC399** [comment]
@ray31245 

> it does work on self-hosted runner, but on Github-Hosted runner is works well.

That looks like a typo in there somewhere!

Does it work on a self-hosted runner?
Does it work on a GitHub-hosted runner?

From which type of runner is your log produced?

I suspect that you are on a self-hosted runner and that Node.js is not installed.

**Comment by ray31245** [comment]
> @ray31245
> 
> > it does work on self-hosted runner, but on Github-Hosted runner is works well.
> 
> That looks like a typo in there somewhere!
> 
> Does it work on a self-hosted runner? Does it work on a GitHub-hosted runner?
> 
> From which type of runner is your log produced?
> 
> I suspect that you are on a self-hosted runner and that Node.js is not installed.

I really has a typo at there. 😅
It does  not work on self-host runner.
I fix the work flow.
```
name: Cypress Integration Test

on:
  workflow_dispatch:

jobs: 
  cypress-run: 
    runs-on: self-hosted 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
      - name: Use Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 18 
      # Install NPM dependencies, cache them correctly
      # and run all Cypress test
      - name: Cypress run
        uses: cypress-io/github-action@v5 
        env: 
          DEBUG: '@cypress/github-action'
        with:
          build: npm run cy:run 
```

Thank you for your feedback, it has been resolved.

**Comment by MikeMcC399** [comment]
@ray31245 

Thanks for posting your solution. 👍🏻 That may help somebody else.

The GitHub-hosted runners all have Node.js 18 installed by default, so this is only an issue of self-hosted runners.
